export interface TextureFallbackDefinition {
  radius: number
  color: number
}

export interface VectorAssetDefinition {
  key: string
  path: string
  width: number
  height: number
  fallback?: TextureFallbackDefinition
}

export interface AnimationDefinition {
  key: string
  frames: string[]
  frameRate: number
}

export const getHudWeaponAssetPath = (iconKey: string) => `assets/hud/weapons/${iconKey.replace(/^weapon-/, '')}.svg`

export const getHudEnemyAssetPath = (iconKey: string) => `assets/units/${iconKey}-idle-0.svg`

export const VECTOR_ASSETS: VectorAssetDefinition[] = [
  {
    key: 'player',
    path: 'assets/units/player-kim-idle-0.png',
    width: 32,
    height: 32,
    fallback: { radius: 14, color: 0x66d9ef },
  },
  {
    key: 'player-idle-1',
    path: 'assets/units/player-kim-idle-1.png',
    width: 32,
    height: 32,
    fallback: { radius: 14, color: 0x66d9ef },
  },
  {
    key: 'player-walk-0',
    path: 'assets/units/player-kim-walk-0.png',
    width: 32,
    height: 32,
    fallback: { radius: 14, color: 0x66d9ef },
  },
  {
    key: 'player-walk-1',
    path: 'assets/units/player-kim-walk-1.png',
    width: 32,
    height: 32,
    fallback: { radius: 14, color: 0x66d9ef },
  },
  {
    key: 'slime',
    path: 'assets/units/slime-idle-0.svg',
    width: 24,
    height: 24,
    fallback: { radius: 12, color: 0x84ff95 },
  },
  {
    key: 'slime-idle-1',
    path: 'assets/units/slime-idle-1.svg',
    width: 24,
    height: 24,
    fallback: { radius: 12, color: 0x84ff95 },
  },
  {
    key: 'spark-slime',
    path: 'assets/units/spark-slime-idle-0.svg',
    width: 26,
    height: 26,
    fallback: { radius: 12, color: 0xffdb6e },
  },
  {
    key: 'spark-slime-idle-1',
    path: 'assets/units/spark-slime-idle-1.svg',
    width: 26,
    height: 26,
    fallback: { radius: 12, color: 0xffdb6e },
  },
  {
    key: 'prism-slime',
    path: 'assets/units/prism-slime-idle-0.svg',
    width: 30,
    height: 30,
    fallback: { radius: 14, color: 0xff9df3 },
  },
  {
    key: 'prism-slime-idle-1',
    path: 'assets/units/prism-slime-idle-1.svg',
    width: 30,
    height: 30,
    fallback: { radius: 14, color: 0xff9df3 },
  },
  {
    key: 'dash-slime',
    path: 'assets/units/dash-slime-idle-0.svg',
    width: 28,
    height: 24,
    fallback: { radius: 12, color: 0xff8f70 },
  },
  {
    key: 'dash-slime-idle-1',
    path: 'assets/units/dash-slime-idle-1.svg',
    width: 28,
    height: 24,
    fallback: { radius: 12, color: 0xff8f70 },
  },
  {
    key: 'orbit-slime',
    path: 'assets/units/orbit-slime-idle-0.svg',
    width: 26,
    height: 26,
    fallback: { radius: 12, color: 0x75c7ff },
  },
  {
    key: 'orbit-slime-idle-1',
    path: 'assets/units/orbit-slime-idle-1.svg',
    width: 26,
    height: 26,
    fallback: { radius: 12, color: 0x75c7ff },
  },
  {
    key: 'needle-wasp',
    path: 'assets/units/needle-wasp-idle-0.svg',
    width: 32,
    height: 28,
    fallback: { radius: 12, color: 0xffb15c },
  },
  {
    key: 'needle-wasp-idle-1',
    path: 'assets/units/needle-wasp-idle-1.svg',
    width: 32,
    height: 28,
    fallback: { radius: 12, color: 0xffb15c },
  },

  {
    key: 'splitter-slime',
    path: 'assets/units/splitter-slime-idle-0.svg',
    width: 28,
    height: 28,
    fallback: { radius: 13, color: 0x9dffb0 },
  },
  {
    key: 'splitter-slime-idle-1',
    path: 'assets/units/splitter-slime-idle-1.svg',
    width: 28,
    height: 28,
    fallback: { radius: 13, color: 0x9dffb0 },
  },
  {
    key: 'shard-sentinel',
    path: 'assets/units/shard-sentinel-idle-0.svg',
    width: 30,
    height: 30,
    fallback: { radius: 14, color: 0xb8e7ff },
  },
  {
    key: 'shard-sentinel-idle-1',
    path: 'assets/units/shard-sentinel-idle-1.svg',
    width: 30,
    height: 30,
    fallback: { radius: 14, color: 0xb8e7ff },
  },
  {
    key: 'mender-slime',
    path: 'assets/units/mender-slime-idle-0.svg',
    width: 26,
    height: 26,
    fallback: { radius: 12, color: 0x8fffd8 },
  },
  {
    key: 'mender-slime-idle-1',
    path: 'assets/units/mender-slime-idle-1.svg',
    width: 26,
    height: 26,
    fallback: { radius: 12, color: 0x8fffd8 },
  },
  {
    key: 'void-orb',
    path: 'assets/units/void-orb-idle-0.svg',
    width: 28,
    height: 28,
    fallback: { radius: 12, color: 0xb096ff },
  },
  {
    key: 'void-orb-idle-1',
    path: 'assets/units/void-orb-idle-1.svg',
    width: 28,
    height: 28,
    fallback: { radius: 12, color: 0xb096ff },
  },
  {
    key: 'crusher-slime',
    path: 'assets/units/crusher-slime-idle-0.svg',
    width: 38,
    height: 34,
    fallback: { radius: 16, color: 0xff7a9f },
  },
  {
    key: 'crusher-slime-idle-1',
    path: 'assets/units/crusher-slime-idle-1.svg',
    width: 38,
    height: 34,
    fallback: { radius: 16, color: 0xff7a9f },
  },
  {
    key: 'lantern-moth',
    path: 'assets/units/lantern-moth-idle-0.svg',
    width: 34,
    height: 30,
    fallback: { radius: 13, color: 0xffe27a },
  },
  {
    key: 'lantern-moth-idle-1',
    path: 'assets/units/lantern-moth-idle-1.svg',
    width: 34,
    height: 30,
    fallback: { radius: 13, color: 0xffe27a },
  },
  {
    key: 'mirror-wisp',
    path: 'assets/units/mirror-wisp-idle-0.svg',
    width: 26,
    height: 30,
    fallback: { radius: 12, color: 0xc6f4ff },
  },
  {
    key: 'mirror-wisp-idle-1',
    path: 'assets/units/mirror-wisp-idle-1.svg',
    width: 26,
    height: 30,
    fallback: { radius: 12, color: 0xc6f4ff },
  },
  {
    key: 'siege-toad',
    path: 'assets/units/siege-toad-idle-0.svg',
    width: 40,
    height: 30,
    fallback: { radius: 16, color: 0x8fd36a },
  },
  {
    key: 'siege-toad-idle-1',
    path: 'assets/units/siege-toad-idle-1.svg',
    width: 40,
    height: 30,
    fallback: { radius: 16, color: 0x8fd36a },
  },
  {
    key: 'slime-boss',
    path: 'assets/units/slime-boss-idle-0.svg',
    width: 56,
    height: 56,
    fallback: { radius: 28, color: 0xd8a6ff },
  },
  {
    key: 'slime-boss-idle-1',
    path: 'assets/units/slime-boss-idle-1.svg',
    width: 56,
    height: 56,
    fallback: { radius: 28, color: 0xd8a6ff },
  },
  {
    key: 'starter-projectile',
    path: 'assets/projectiles/starter-projectile.svg',
    width: 20,
    height: 12,
    fallback: { radius: 5, color: 0xf8fafc },
  },
  {
    key: 'acid-projectile',
    path: 'assets/projectiles/acid-projectile.svg',
    width: 20,
    height: 12,
    fallback: { radius: 5, color: 0xc1ff72 },
  },
  {
    key: 'frost-projectile',
    path: 'assets/projectiles/frost-projectile.svg',
    width: 20,
    height: 12,
    fallback: { radius: 5, color: 0x9ce7ff },
  },
  {
    key: 'storm-projectile',
    path: 'assets/projectiles/storm-projectile.svg',
    width: 20,
    height: 12,
    fallback: { radius: 5, color: 0xd4b5ff },
  },
  {
    key: 'arc-projectile',
    path: 'assets/projectiles/arc-projectile.svg',
    width: 20,
    height: 12,
    fallback: { radius: 5, color: 0xffd866 },
  },
  {
    key: 'spark-projectile',
    path: 'assets/projectiles/spark-projectile.svg',
    width: 22,
    height: 12,
    fallback: { radius: 5, color: 0xfff06a },
  },
  {
    key: 'mist-projectile',
    path: 'assets/projectiles/mist-projectile.svg',
    width: 22,
    height: 14,
    fallback: { radius: 6, color: 0xc4f1ff },
  },
  {
    key: 'needle-projectile',
    path: 'assets/projectiles/needle-projectile.svg',
    width: 24,
    height: 8,
    fallback: { radius: 5, color: 0xffb15c },
  },
  {
    key: 'gel-shard',
    path: 'assets/loot/gel-shard.svg',
    width: 22,
    height: 22,
    fallback: { radius: 10, color: 0x7dffb0 },
  },
  {
    key: 'acid-core',
    path: 'assets/loot/acid-core.svg',
    width: 22,
    height: 22,
    fallback: { radius: 10, color: 0xb4ff5e },
  },
  {
    key: 'frost-mote',
    path: 'assets/loot/frost-mote.svg',
    width: 22,
    height: 22,
    fallback: { radius: 10, color: 0x83d5ff },
  },
  {
    key: 'spark-knot',
    path: 'assets/loot/spark-knot.svg',
    width: 22,
    height: 22,
    fallback: { radius: 10, color: 0xffd866 },
  },
  {
    key: 'mist-bead',
    path: 'assets/loot/mist-bead.svg',
    width: 22,
    height: 22,
    fallback: { radius: 10, color: 0xc4f1ff },
  },
  {
    key: 'tuning-capsule',
    path: 'assets/loot/tuning-capsule.svg',
    width: 22,
    height: 22,
    fallback: { radius: 10, color: 0xff9df3 },
  },
  {
    key: 'chitin-needle',
    path: 'assets/loot/chitin-needle.svg',
    width: 22,
    height: 22,
    fallback: { radius: 10, color: 0xffb15c },
  },
  {
    key: 'heart-pickup',
    path: 'assets/loot/heart-pickup.svg',
    width: 24,
    height: 24,
    fallback: { radius: 11, color: 0xff5c8a },
  },
  {
    key: 'magnet-pickup',
    path: 'assets/loot/magnet-pickup.svg',
    width: 24,
    height: 24,
    fallback: { radius: 11, color: 0x66d9ef },
  },
  {
    key: 'weapon-starter-blaster',
    path: getHudWeaponAssetPath('weapon-starter-blaster'),
    width: 96,
    height: 96,
  },
  {
    key: 'weapon-acid-sprayer',
    path: getHudWeaponAssetPath('weapon-acid-sprayer'),
    width: 96,
    height: 96,
  },
  {
    key: 'weapon-frost-lance',
    path: getHudWeaponAssetPath('weapon-frost-lance'),
    width: 96,
    height: 96,
  },
  {
    key: 'weapon-storm-cannon',
    path: getHudWeaponAssetPath('weapon-storm-cannon'),
    width: 96,
    height: 96,
  },
  {
    key: 'weapon-arc-loom',
    path: getHudWeaponAssetPath('weapon-arc-loom'),
    width: 96,
    height: 96,
  },
  {
    key: 'weapon-spark-carbine',
    path: getHudWeaponAssetPath('weapon-spark-carbine'),
    width: 96,
    height: 96,
  },
  {
    key: 'weapon-mist-vortex',
    path: getHudWeaponAssetPath('weapon-mist-vortex'),
    width: 96,
    height: 96,
  },
  {
    key: 'weapon-slime-glaive',
    path: getHudWeaponAssetPath('weapon-slime-glaive'),
    width: 96,
    height: 96,
  },
  {
    key: 'weapon-prism-cutter',
    path: getHudWeaponAssetPath('weapon-prism-cutter'),
    width: 96,
    height: 96,
  },
  {
    key: 'weapon-needle-fan',
    path: getHudWeaponAssetPath('weapon-needle-fan'),
    width: 96,
    height: 96,
  },
]

export const IDLE_ANIMATIONS: AnimationDefinition[] = [
  { key: 'player-idle', frames: ['player', 'player-idle-1'], frameRate: 4 },
  { key: 'player-move', frames: ['player-walk-0', 'player-walk-1'], frameRate: 8 },
  { key: 'slime-idle', frames: ['slime', 'slime-idle-1'], frameRate: 3 },
  { key: 'spark-slime-idle', frames: ['spark-slime', 'spark-slime-idle-1'], frameRate: 4 },
  { key: 'prism-slime-idle', frames: ['prism-slime', 'prism-slime-idle-1'], frameRate: 4 },
  { key: 'dash-slime-idle', frames: ['dash-slime', 'dash-slime-idle-1'], frameRate: 7 },
  { key: 'orbit-slime-idle', frames: ['orbit-slime', 'orbit-slime-idle-1'], frameRate: 5 },
  { key: 'needle-wasp-idle', frames: ['needle-wasp', 'needle-wasp-idle-1'], frameRate: 7 },
  { key: 'splitter-slime-idle', frames: ['splitter-slime', 'splitter-slime-idle-1'], frameRate: 5 },
  { key: 'shard-sentinel-idle', frames: ['shard-sentinel', 'shard-sentinel-idle-1'], frameRate: 3 },
  { key: 'mender-slime-idle', frames: ['mender-slime', 'mender-slime-idle-1'], frameRate: 4 },
  { key: 'void-orb-idle', frames: ['void-orb', 'void-orb-idle-1'], frameRate: 4 },
  { key: 'crusher-slime-idle', frames: ['crusher-slime', 'crusher-slime-idle-1'], frameRate: 2 },
  { key: 'lantern-moth-idle', frames: ['lantern-moth', 'lantern-moth-idle-1'], frameRate: 8 },
  { key: 'mirror-wisp-idle', frames: ['mirror-wisp', 'mirror-wisp-idle-1'], frameRate: 4 },
  { key: 'siege-toad-idle', frames: ['siege-toad', 'siege-toad-idle-1'], frameRate: 3 },
  { key: 'slime-boss-idle', frames: ['slime-boss', 'slime-boss-idle-1'], frameRate: 2 },
]
